---

- name: download latest amd64 release
  when: ansible_facts.architecture == 'x86_64'
  get_url:
    url: "{{ caddy_amd64_linux_binary_url }}"
    dest: "{{ caddy_binary_path }}"
    owner: root
    group: root
    mode: a+x
  ignore_errors: true
  
- name: download latest arm64 release
  when: ansible_facts.architecture == 'aarch64'
  get_url:
    url: "{{ caddy_arm64_linux_binary_url }}"
    dest: "{{ caddy_binary_path }}"
    owner: root
    group: root
    mode: a+x
  ignore_errors: true

- name: Add the caddy user
  ansible.builtin.user:
    name: "{{ caddy_user }}"
    group: "{{ caddy_group }}"

- name: install caddy systemd service
  template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644

- name: create caddy log directory
  file:
    path: "{{ caddy_log_path }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0755

- name: touch caddy.log
  ansible.builtin.file:
    path: "{{ caddy_log_path }}/caddy.log"
    state: touch
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0755

- name: restart caddy service
  ansible.builtin.systemd:
    name: caddy
    daemon_reload: true
    enabled: yes